# Generated by Django 3.0.5 on 2020-04-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
