# Generated by Django 3.0.4 on 2020-05-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderdBy',
            field=models.CharField(default='', max_length=100),
        ),
    ]
